version: '3.8'

services:
  nestjs:
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: nestjs-app
    ports:
      - '3000:3000'
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - nestjs
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
